[project]
name = "sta"
version = "1.0.0"
authors = [
  { name="Juan Urrego", email="w.alarconc@uniandes.edu.co" },
]
description = "Proyecto STA"
readme = "README.md"
requires-python = ">=3.10"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  ".", "src",
]